SELECT ALL_TAB_COMMENTS.OWNER
      ,ALL_TAB_COMMENTS.TABLE_NAME
      ,ALL_TAB_COMMENTS.COMMENTS
      ,ALL_TAB_COLUMNS.COLUMN_ID
      ,ALL_TAB_COLUMNS.COLUMN_NAME
      ,ALL_TAB_COLUMNS.DATA_TYPE
      ,ALL_TAB_COLUMNS.DATA_LENGTH
      ,ALL_TAB_COLUMNS.NULLABLE
      ,ALL_COL_COMMENTS.COMMENTS
--      ,ALL_TAB_COLUMNS.DATA_PRECISION
--      ,ALL_TAB_COLUMNS.DATA_SCALE
  FROM ALL_COL_COMMENTS
      ,ALL_TAB_COLUMNS
      ,ALL_TAB_COMMENTS
 WHERE ALL_TAB_COMMENTS.OWNER = ALL_TAB_COLUMNS.OWNER
   AND ALL_TAB_COMMENTS.OWNER = ALL_COL_COMMENTS.OWNER
   AND ALL_TAB_COMMENTS.TABLE_NAME = ALL_TAB_COLUMNS.TABLE_NAME
   AND ALL_TAB_COMMENTS.TABLE_NAME = ALL_COL_COMMENTS.TABLE_NAME
   AND ALL_TAB_COLUMNS.COLUMN_NAME = ALL_COL_COMMENTS.COLUMN_NAME
   AND ALL_TAB_COLUMNS.OWNER = UPPER('USER명')
-- AND ALL_TAB_COMMENTS.TABLE_NAME = UPPER('테이블명')
 ORDER BY ALL_TAB_COMMENTS.OWNER      ASC
         ,ALL_TAB_COMMENTS.TABLE_NAME ASC
         ,ALL_TAB_COLUMNS.COLUMN_ID   ASC